openapi: "3.1.0"
info:
  title: "hostinger API"
  description: "hostinger API"
  version: "1.0.0"
servers:
  - url: "https://hostinger"
paths:
  /internal/hosting/process/list:
    get:
      summary: "GET internal/hosting/process/list"
      operationId: "getAllProcesses"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /internal/hosting/process/{id}:
    get:
      summary: "GET internal/hosting/process/{id}"
      operationId: "getProductById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /internal/hosting/process/{id}/start:
    get:
      summary: "GET internal/hosting/process/{id}/start"
      operationId: "startProcess"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /internal/hosting/process/{id}/stop:
    get:
      summary: "GET internal/hosting/process/{id}/stop"
      operationId: "stopProcess"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /internal/hosting/process/{id}/restart:
    get:
      summary: "GET internal/hosting/process/{id}/restart"
      operationId: "restartProcess"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"