openapi: "3.1.0"
info:
  title: "hostinger API"
  description: "hostinger API"
  version: "1.0.0"
servers:
  - url: "https://hostinger"
paths:
  /internal/hosting/virtualized/list:
    get:
      summary: "GET internal/hosting/virtualized/list"
      operationId: "getAllVisualizations"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /internal/hosting/virtualized/{id}:
    get:
      summary: "GET internal/hosting/virtualized/{id}"
      operationId: "getVirtualizedById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /internal/hosting/virtualized/{id}/start:
    get:
      summary: "GET internal/hosting/virtualized/{id}/start"
      operationId: "start"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /internal/hosting/virtualized/{id}/stop:
    get:
      summary: "GET internal/hosting/virtualized/{id}/stop"
      operationId: "stop"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /internal/hosting/virtualized/{id}/reset:
    get:
      summary: "GET internal/hosting/virtualized/{id}/reset"
      operationId: "reset"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /internal/hosting/virtualized/{id}/kill:
    get:
      summary: "GET internal/hosting/virtualized/{id}/kill"
      operationId: "kill"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /internal/hosting/virtualized/{id}/pause:
    get:
      summary: "GET internal/hosting/virtualized/{id}/pause"
      operationId: "pause"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /internal/hosting/virtualized/{id}/resume:
    get:
      summary: "GET internal/hosting/virtualized/{id}/resume"
      operationId: "resume"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"