openapi: "3.1.0"
info:
  title: "hostinger API"
  description: "hostinger API"
  version: "1.0.0"
servers:
  - url: "https://hostinger"
paths:
  /internal/payment/{provider}/webhook:
    get:
      summary: "GET internal/payment/{provider}/webhook"
      operationId: "paymentGet"
      parameters:
        - name: "provider"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
    post:
      summary: "POST internal/payment/{provider}/webhook"
      operationId: "paymentPost"
      parameters:
        - name: "provider"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"