openapi: "3.1.0"
info:
  title: "hostinger API"
  description: "hostinger API"
  version: "1.0.0"
servers:
  - url: "https://hostinger"
paths:
  /internal/ecommerce/product/list:
    get:
      summary: "GET internal/ecommerce/product/list"
      operationId: "getAllProducts"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /internal/ecommerce/product/checksum:
    get:
      summary: "GET internal/ecommerce/product/checksum"
      operationId: "getChecksumOfAllProducts"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /internal/ecommerce/product/{id}:
    get:
      summary: "GET internal/ecommerce/product/{id}"
      operationId: "getProductById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /internal/ecommerce/product/{id}/checksum:
    get:
      summary: "GET internal/ecommerce/product/{id}/checksum"
      operationId: "getProductChecksumById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"