flowchart TD
    Core[Hostinger] --> Process[Process]
    Core --> Virtualized[Virtualized]
    Virtualized --> Request
    Process --> Request
    Request --> Module
    Module --> State
    State --> Start
    State --> Stop
    State --> Create
    State --> ...
    Module --> Status
    Start --> Response
    Stop --> Response
    Create --> Response
    ... --> Response
    Status --> Response
    Response --> Core
