openapi: "3.1.0"
info:
  title: "hostinger API"
  description: "hostinger API"
  version: "1.0.0"
servers:
  - url: "https://hostinger"
paths:
  /module/list:
    get:
      summary: "GET module/list"
      operationId: "list"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  type: "string"
  /module/start/{pluginId}:
    get:
      summary: "GET module/start/{pluginId}"
      operationId: "start"
      parameters:
        - name: "pluginId"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "integer"
                format: "int32"
  /module/stop/{pluginId}:
    get:
      summary: "GET module/stop/{pluginId}"
      operationId: "stop"
      parameters:
        - name: "pluginId"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "integer"
                format: "int32"