openapi: "3.1.0"
info:
  title: "hostinger API"
  description: "hostinger API"
  version: "1.0.0"
servers:
  - url: "https://hostinger"
paths:
  /internal/attachment/{id}:
    get:
      summary: "GET internal/attachment/{id}"
      operationId: "attatchmentGet"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"